### ISSUE TITLE
Adding wheel to pypi

### ISSUE THREAD

**Issue by daveisfera** [AstralScribe/python-audio#2]
Thanks for getting this [published to pypi](#1 ) but it requires quite a few packages (`cmake`, `gcc`/`g++` and `pybind11`) to do the build during the install. It would be nice if wheels were available so it could be [installed on most common platforms](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/).

**Comment by AstralScribe** [comment]
I tried earlier, and was able to build on linux_x86_64 but pypi rejected the platform. So, I will look through the article and try to make wheels available for common platforms.

**Comment by AstralScribe** [comment]
Wheels has been added for linux and macos.

**Comment by daveisfera** [comment]
That worked! Thanks!
